
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repsy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/repsy
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STORAGE_STRATEGY=file-system
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - db
      - minio
    networks:
      - repsy-net

  db:
    image: postgres:15
    container_name: repsy-db
    environment:
      POSTGRES_DB: repsy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - repsy-net

  minio:
    image: minio/minio
    container_name: repsy-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - repsy-net

volumes:
  minio-data:

networks:
  repsy-net:


