
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repsy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/repsy_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_SHOW-SQL=true
      - STORAGE_STRATEGY=file-system
      - STORAGE_MINIO_URL=http://minio:9000
      - STORAGE_MINIO_ACCESS_KEY=minioadmin
      - STORAGE_MINIO_SECRET_KEY=minioadmin
      - STORAGE_MINIO_BUCKET=miniobucket

    depends_on:
      - db
      - minio
    networks:
      - repsy-net

  db:
    image: postgres:15
    container_name: repsy-db
    environment:
      POSTGRES_DB: repsy_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - repsy-net

  minio:
    image: minio/minio
    container_name: repsy-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - repsy-net

volumes:
  minio-data:

networks:
  repsy-net:


