CREATE TABLE package
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      VARCHAR(255),
    name         VARCHAR(255),
    author       VARCHAR(255)                            NOT NULL,
    dependencies JSONB,
    uploaded_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_package PRIMARY KEY (id)
);